### ISSUE TITLE
Able to collect direct links to download latest albums

### ISSUE THREAD

**Issue by rajupenumatsa** [rajupenumatsa/mp3download#1]
- [x] Build a scraper to go and monitor https://naasongs.com/telugu-songs-b/ site for latest albums.
- [x] Navigate to album page.
- [x] Check if a download link is available to download all the songs as a zip file and collect it.
- [x] Iterate this whole process until it collects available album download links for all albums available in the given link.

**Comment by kobirbd18** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
dung1t, @Blaine-Mason, @joestanl3y, @loopiezlol, @amarnp85, @yingnengd, @jinczing, @RevoStaffone, @calvinturner, @timouwerkerk, @jonabe, @wayhome, @Prat617, @Quantbrinx, @seguidor777, @baryshev, @lguoca, @dm267, @ChocoShell, @crazypythonista, @hn2, @nova-land, @ben-jit, @bprabhuin, @thysruben, @MihirVangani17, @billtron, @ProfitPhenom, @royburns, @dabao1257, @Resmung0, @skssu, @maxclchen, @rseverinop, @loki-zhou, @secp600k1, @kaczy44, @nigerninja, @oyesindhi, @tiwilliam, @oakejp12, @jordankiggundu, @SergKlein, @kdkiss, @realwaynesun, @i-aztec, @athon-millane, @bz77, @realm520, @danteGPTdmarienko, @SamAbdelbadie, @lovepocky, @Jbond007-11, @tngdr, @GwakJunwoo, @Adeel-Intizar, @dimx9173, @yongdono, @ramishni, @hanbinggan, @Marco-Christiani, @RGDub, @daviddwlee84, @skzv, @hungha11, @Chris6622, @doomedkiddo, @brandonyano, @dhiruyaga, @nitinongit, @zerak, @benstear, @mayank160920, @sopay, @vorotynsky, @sseveran, @vipinbhagat123, @bprabhuin, @zhuoqiang, @Armstrm6, @aaiken1, @den4ess, @mohadmohammadi, @ForrestDevs, @nikhilranjan7, @eLoyyyyy, @yasdelayu, @benedoug, @cpowlett, @pra1had, @Vandr10, @MilleniumSpark, @gangodu, @LechedeRoma, @DJinnzNathan, @ducga1998, @thisismeleaving, @ddanielmmonteiro, @unijoy

**Comment by kobirbd18** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
